#+title: 其他备忘

* 只查询手动安装的软件包
** Homebrew
*** 方法1
https://github.com/Homebrew/homebrew-bundle

这个会在当前目录下生成文件，每个软件包都标注了tap,formula,cask等

但需要注意，它同时会包含曾经安装，现已卸载，但还没有被清理的软件包

#+begin_src shell
brew bundle dump
#+end_src

不会显示 *brew install --cask <pkg>* 中的pkg名，只显示cask源。

*** 方法2
#+begin_src shell
brew list --full-name --installed-on-request

# 或者

brew leaves -r
#+end_src

上面两个命令完全等价，但不会像bundle那样显示详细信息。

所以需要需要结合下面命令。

#+begin_src shell
brew list --cask
#+end_src

不会显示 *brew install --cask <pkg>* 中的pkg名，只显示cask源。

*** cask
想要知道 *brew install --cask <pkg>* 中的pkg名，可以用以下命令。

#+begin_src shell
brew info --cask CASKNAME

# 或者

brew info CASKNAME
#+end_src

查看 *Name* 字段。

** npm
#+begin_src shell
npm list --global --parseable --depth=0 | grep 'node_modules' | xargs basename | grep -v -E '(npm|corepack)' | paste -s -d' ' -
#+end_src

** pip
虽然不是完全准确，但勉强能用。

#+begin_src shell
pip list --not-required | grep -v 'pip' | tail -n +3 | awk '{print $1}' | paste -s -d' ' -
#+end_src

** go
查了半天资料，没找到如何列出安装到$GOPATH中的所有软件包。

还是查 ~$GOPATH/bin~ 目录把。

* 选择最快的 ~apt~ 源
#+begin_src shell
apt install netselect-apt

netselect-apt

cp /etc/apt/sources.list /etc/apt/sources.list.backup
cp sources.list /etc/apt/sources.list

apt update
#+end_src

把生成的source.list复制到
* [[https://pandoc.org/][Pandoc]]
#+begin_quote
A universal document converter
#+end_quote

各种文档格式之间相互转换，支持市面上看到的绝大多数文档格式。

#+begin_src shell
pandoc -f markdown -t org -o output.org input.md
#+end_src

* FFmpeg
#+begin_quote
A complete, cross-platform solution to record, convert and stream audio and video.
#+end_quote

#+begin_src shell
# 旋转视频
ffmpeg -display_rotation -90 -i INPUT -c copy OUTPUT

# 修改视频的分辨率
ffmpeg -i INPUT -vf scale=1440:-1 OUTPUT

# 剪辑视频片段
ffmpeg -i INPUT -ss 00:05:10 -to 00:15:30 -c copy OUPUT

# 拼接多个视频
touch files.txt
echo "file '/path/to/input/file1'"
echo "file '/path/to/input/file2'"
echo "file '/path/to/input/file3'"

ffmpeg -f concat -i files.txt -c copy OUTPUT
#+end_src

* MariaDB/MySQL
保证utf-8为默认字符集。

#+begin_example
[client]
default-character-set = utf8mb4

[mysql]
default-character-set = utf8mb4

[mysqld]
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_520_ci
#+end_example

* 字体类型
#+begin_quote
PostScript是主要用于电子产业和桌面出版领域的一种页面描述语言和编程语言。
#+end_quote

** TTF (TrueType Font)
- 1980年代末由Microsoft和Apple共同开发。
- 保证屏幕与打印输出一致性。
- 可以随意缩放、旋转，不会出现锯齿。
- 主要操作系统用。
- 兼容性高。
- 扩展名是.ttf。

**  OTF (OpenType Font)
- 由Microsoft和Adobe共同开发。
- 基于TTF开发，TTF的超集。
- 支持的字符集更大。
- 包含TrueType的扩展名是.ttf
- 包含PostScript的扩展名是.otf

** EOT (Embeded Open Type)
- 只能用在IE。
- 网页字体，体积小。
- 已死。

** WOFF (Web Open Font Format)
- 有Mozilla基金会、微软、Opera合作开发。
- 网页字体，体积小。
- 主流浏览器都支持。

** WOFF2 (Web Open Font Format 2)
- WOFF的升级版。
- 体积更小了。

** VF (Variable Font)
- [[https://github.com/FoxDaxian/memory/issues/4][更小更灵活的字体]]

* 英文等宽字体
- DejaVu Sans Mono
- Fira Code
- JetBrains Mono
- Source Code Pro
- Menlo
- Monaco

* CJK（中日韩）等宽字体
CJK字符正好是拉丁字符的两倍宽度。

- Sarasa Mono SC
- Noto Sans Mono CJK SC
- Ubuntu Mono

* Tomcat虚拟主机
bin/catalina.sh文件中写到。

#+begin_example
# -----------------------------------------------------------------------------
# Control Script for the CATALINA Server
#
# Environment Variable Prerequisites
#
#   Do not set the variables in this script. Instead put them into a script
#   setenv.sh in CATALINA_BASE/bin to keep your customizations separate.
#
#+end_example

按照指引，创建bin/setenv.sh文件。

#+begin_src shell
#!/bin/bash

# 也可以写绝对路径。
export JAVA_HOME="$(jenv javahome)"
export JAVA_OPTS="-Xmx2048m -Xms1024m -XX:PermSize=128m -XX:MaxPermSize=256m -Dfile.encoding=UTF-8"
#+end_src shell

虚拟机主机配置在conf/server.xml。

#+begin_src nxml
<!-- conf/server.xml -->

  <!-- ... -->

  <Engine name="Catalina" defaultHost="localhost">

    <!-- ... -->

    <!-- 添加以下内容 -->
    <Host
        <!-- 域名不需要写端口 -->
        name="mydomain.com"
        <!-- 编译产出目录的绝对路径 -->
        appBase="/path/to/the/build/directory/of/your/java/project"
        unpackWARs="true"
        autoDeploy="true">

        <!-- 至少在Tomcat7，path="" 和 docBase=""不能少 -->
        <Context
            path=""
            docBase="/path/to/the/build/directory/of/your/java/project" crossContext="false"
            reloadable="true"
        />

        <!-- ... -->

    </Host>

    <!-- ... -->

  </Engine>

  <!-- ... -->
#+end_src

* [[https://github.com/lsyncd/lsyncd][Lsyncd]]
#+begin_quote
Live Syncing(Mirror) Daemon
#+end_quote

基于inotify或fsevents通过rsync等传输工具实现实时同步文件。

* XLFD (X Logical Font Description)
密文版的字体描述。

#+begin_example
-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso8859-1

-bitstream-charter-medium-r-normal--12-120-75-75-p-68-iso8859-1

-ns-*-*-*-*-*-10-*-*-*-*-*-fontset-standard

-*-Menlo-regular-normal-normal-*-20-*-*-*-m-0-fontset-auto1
#+end_example

由14个对象构成，格式如下。

|  N | Property         | 含义      | Definition                        |
|----+------------------+-----------+-----------------------------------|
|  1 | FOUNDRY          | 厂商      | 字体的开发商、设计者等标识。          |
|    | fndry            |           | FamilyName相同的时候用来区分的。     |
|----+------------------+-----------+-----------------------------------|
|  2 | FAMILY_NAME      | 字族      | 就是font-family                   |
|    | fmly             |           |                                   |
|----+------------------+-----------+-----------------------------------|
|  3 | WEIGHT_NAME      | 粗细      | medium, bold这种...               |
|    | wght             |           |                                   |
|----+------------------+-----------+-----------------------------------|
|  4 | SLANT            | 倾斜      | 描述倾斜方向：                      |
|    | slant            |           |                                   |
|    |                  |           | - r (Roman-no slant)              |
|    |                  |           | - i (Italic-slant right)          |
|    |                  |           | - o (Oblique-slant right)         |
|    |                  |           | - ri (Reverse Italic-slant left)  |
|    |                  |           | - ro (Reverse Oblique-slant left) |
|----+------------------+-----------+-----------------------------------|
|  5 | SETWIDTH_NAME    | 铅字宽度   | 是否有横向拉伸或挤压。               |
|    | sWdth            |           | normal, narrow, condensed         |
|----+------------------+-----------+-----------------------------------|
|  6 | ADD_STYLE        | 补充样式   | 厂商决定。                         |
|    | adstyl           |           | sans, serif                       |
|----+------------------+-----------+-----------------------------------|
|  7 | PIXEL_SIZE       | 字符尺寸   | 单位是像素。*或0表示可变尺寸。        |
|    | pxlsz            |           |                                   |
|----+------------------+-----------+-----------------------------------|
|  8 | POINT_SIZE       | 字符尺寸   | 单位是十分之一“点”                 |
|    | ptSz             |           |                                   |
|----+------------------+-----------+-----------------------------------|
|  9 | RESOLUTION_X     | 水平分辨率 | 单位是像素或DPI                     |
|    | resx             |           |                                   |
|----+------------------+-----------+-----------------------------------|
| 10 | RESOLUTION_Y     | 垂直分辨率 | 同RESOLUTION_Y                    |
|    | resy             |           |                                   |
|----+------------------+-----------+-----------------------------------|
| 11 | SPACING          | 留白方式   | - m (Monospace - 等宽)            |
|    | spc              |           | - p (Proportional space- 协调的)   |
|    |                  |           | - c (Character cell)              |
|----+------------------+-----------+-----------------------------------|
| 12 | AVERAGE_WIDTH    | 平均宽度   | 单位是十分之一像素                   |
|    | avgWdth          |           |                                   |
|----+------------------+-----------+-----------------------------------|
| 13 | CHARSET_REGISTRY | 注册字符集 | iso10646, gb18030, gb2312等       |
|    | rgstry           | 字元集     |                                   |
|----+------------------+-----------+-----------------------------------|
| 14 | CHARSET_ENCODING | 字符编码   | 没搞懂是什么。                      |
|    | encdng           |           |                                   |
|----+------------------+-----------+-----------------------------------|
